apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  RAILS_PORT: "3000"
  GRAFANA_USER: admin
  GRAFANA_PASSWORD: senhadaboa