apiVersion: v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedulling-postgres
  template:
    metadata:
      labels:
        app: schedulling-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2
        envFrom:
        - configMapRef:
            name: schedulling-configmap
        ports:
        - containerPort: 5432